=== ChunYapBeep/BAIT3343-assignment/app/XML/user/userOrder.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT users (user+)>
<!ELEMENT user (name, email, ordered?)>
<!ATTLIST user id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT ordered (meal+)>
<!ELEMENT meal (name, price, quantity, totalprice, date)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price currency CDATA #REQUIRED>
<!ELEMENT quantity (#PCDATA)>
<!ATTLIST quantity unit CDATA #REQUIRED>
<!ELEMENT totalprice (#PCDATA)>
<!ATTLIST totalprice currency CDATA #REQUIRED>
<!ELEMENT date (#PCDATA)>

=== ChunYapBeep/BAIT3343-assignment/app/XML/user/userOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE users SYSTEM "userOrder.dtd">
<users>
  <user id="1">
    <name>John</name>
    <email>john@gmail.com</email>
  </user>
  <user id="2">
    <name>Fo Yoo</name>
    <email>foyotee1@gmail.com</email>
    <ordered>
      <meal>
        <name>Taiwanese Fried Chicken</name>
        <price currency="RM">15.9</price>
        <quantity unit="plate">2</quantity>
        <totalprice currency="RM">31.8</totalprice>
        <date>2023-05-04</date>
      </meal>
      <meal>
        <name>Dumpling</name>
        <price currency="RM">15.9</price>
        <quantity unit="plate">1</quantity>
        <totalprice currency="RM">15.9</totalprice>
        <date>2023-05-04</date>
      </meal>
    </ordered>
  </user>
  <user id="3">
    <name>alex</name>
    <email>alex@gmail.com</email>
  </user>
  <user id="4">
    <name>junhong</name>
    <email>junhong@gmail.com</email>
  </user>
  <user id="5">
    <name>bungseng</name>
    <email>bungseng@gmail.com</email>
    <ordered>
      <meal>
        <name>Dumpling</name>
        <price currency="RM">15.9</price>
        <quantity unit="plate">1</quantity>
        <totalprice currency="RM">15.9</totalprice>
        <date>2023-05-04</date>
      </meal>
      <meal>
        <name>Spicy Bamboo Salad</name>
        <price currency="RM">15.9</price>
        <quantity unit="plate">1</quantity>
        <totalprice currency="RM">15.9</totalprice>
        <date>2023-05-04</date>
      </meal>
    </ordered>
  </user>
  <user id="6">
    <name>Chun Yappp</name>
    <email>teefy-wm20@student.tarc.edu.my</email>
    <ordered>
      <meal>
        <name>Chicken Wonton Cup</name>
        <price currency="RM">12.9</price>
        <quantity unit="plate">1</quantity>
        <totalprice currency="RM">12.9</totalprice>
        <date>2023-05-04</date>
      </meal>
      <meal>
        <name>Shrimp</name>
        <price currency="RM">79.99</price>
        <quantity unit="plate">1</quantity>
        <totalprice currency="RM">79.99</totalprice>
        <date>2023-05-04</date>
      </meal>
      <meal>
        <name>Grass Jelly</name>
        <price currency="RM">10.99</price>
        <quantity unit="plate">1</quantity>
        <totalprice currency="RM">10.99</totalprice>
        <date>2023-05-04</date>
      </meal>
      <meal>
        <name>Gong Zai Mian</name>
        <price currency="RM">12.99</price>
        <quantity unit="plate">1</quantity>
        <totalprice currency="RM">12.99</totalprice>
        <date>2023-05-04</date>
      </meal>
    </ordered>
  </user>
  <user id="10">
    <name>chunyap</name>
    <email>chunyap@gmail.com</email>
    <ordered>
      <meal>
        <name>Chicken Wonton Cup</name>
        <price currency="RM">12.9</price>
        <quantity unit="plate">1</quantity>
        <totalprice currency="RM">12.9</totalprice>
        <date>2023-05-09</date>
      </meal>
    </ordered>
  </user>
  <user id="11">
    <name>Fo Yo</name>
    <email>foyotee@gmail.com</email>
    <ordered>
      <meal>
        <name>Chicken Wonton Cup</name>
        <price currency="RM">12.9</price>
        <quantity unit="plate">1</quantity>
        <totalprice currency="RM">12.9</totalprice>
        <date>2023-05-09</date>
      </meal>
      <meal>
        <name>Taiwanese Fried Chicken</name>
        <price currency="RM">15.9</price>
        <quantity unit="plate">1</quantity>
        <totalprice currency="RM">15.9</totalprice>
        <date>2023-05-09</date>
      </meal>
    </ordered>
  </user>
</users>
